# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41442129cbb964f4f93fa86049cb6e0954b4f3cb4fbda38acdd8ea25aee7eb3a444f140b0c0f0a366fb645548632b857fa2a40ac3775614ddc6e823b2407a3ba

test:
  secret_key_base: 1c2dd82fddd7981e12dc9ea12dfc7a8efabbdefd3e0e3be248f588b9b65738123f3a991c99306332c9eb14105de321ae1852193a601c703e97dd338d660e7db7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
